config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController 
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to events_path(@event), notice: "L'évènement a bien été créé"
    else
      render :new
    end
  end

  def edit
  end

  def update
    @event.update(event_params)
    redirect_to events_path(@event), notice: "L'évènement a bien été mis à jour"
  end

  def destroy
    @event.destroy
    redirect_to events_path(@event), notice: "L'évènement a bien été supprimé"
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :start_date, :end_date)
  end

  def set_event
    @event = Event.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/edit.html.erb
<div class="container">  
  <h3 class="form-group">Veuillez entrer vos modifications</h3>

    <%= form_with model: @event, method: :patch do |f| %>
      <div class="form-group">
        <%= f.label :name, "Indiquez le nom" %>
        <%= f.text_field :name, class:"form-control", placeholder:"(32 caractères maximum)" %>
      </div>
      <div class="form-group">
        <%= f.label :description, "Ajoutez une description" %>
        <%= f.text_area :description, class:"form-control" %>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col">
            <%= f.label :start_date, "Indiquez le début de l'évènement" %>
            <%= f.date_select :start_date, class:"form-control" %>
          </div>
          <div class="col">
            <%= f.label :end_date, "Indiquez la date de fin" %>
            <%= f.date_select :end_date, class:"form-control" %>
          </div>
        </div>
      </div>
          <div class="form-group">
        <%= f.submit class:"btn btn-primary btn-lg btn-block" %>
      </div>
    <% end %>

  <p><%= link_to 'Back to the main page', events_path %></p>
</div>

app/views/events/index.html.erb
<div class="container">  
  <h1 class="title">Liste des évènements</h1>
  <div class="container">
    <% @events.each do |event| %>
      <div class="row">
        <div class="col-md">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title"><%= event.name %></h5>
                <p class="card-text"><%= event.description %></p>
                <p class="card-link"><%= link_to "Voir les détails", event_path(event)  %></p>
              </div>
            </div>

      </div> 
    </div>
    <% end %>
  </div>
  <button class="btn btn-success"><%= link_to "Nouvel évènement ?", new_event_path %></button>
</div>

app/views/events/new.html.erb
<div class="container">  
  <h3 class="title">Veuillez entrer les détails de votre nouvel évènement</h3>

    <%= form_with model: @event, method: :post do |f| %>
      <div class="form-group">
        <%= f.label :name, "Indiquez le nom" %>
        <%= f.text_field :name, class:"form-control", placeholder:"(32 caractères maximum)" %>
      </div>
      <div class="form-group">
        <%= f.label :description, "Ajoutez une description" %>
        <%= f.text_area :description, class:"form-control" %>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col">
            <%= f.label :start_date, "Indiquez le début de l'évènement" %>
            <%= f.datetime_field :start_date, class:"form-control" %>
          </div>
          <div class="col">
            <%= f.label :end_date, "Indiquez la date de fin" %>
            <%= f.datetime_field :end_date, class:"form-control" %>
          </div>
        </div>
      </div>
          <div class="form-group">
        <%= f.submit class:"btn btn-primary btn-lg btn-block" %>
      </div>
    <% end %>

  <p><%= link_to "Retour à l'accueil", events_path %></p>
</div>

app/views/events/show.html.erb
<div class="container">
  <h1><%= @event.name %></h1>
  <p><%= @event.description %></p>
  <p>Date de début: <%= @event.start_date %></p>
  <p>Date de fin: <%= @event.end_date %></p>
  <%= link_to "Retour à la liste", events_path  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KumojinTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="container-fluid">
    <%= link_to events_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dus151ezt/image/upload/v1657990237/Kumojin-test/logo_wcgekk.png" %>
    <% end %>
    <div class="menu">
      <div class="a1">
        <%= link_to "Liste", events_path %>
      </div>
      <div class="a1">
        <%= link_to "Nouvel évènement ?", new_event_path %>
      </div>
    </div>
  </div>
</div>